encoding: utf-8
livereload: true

url: "https://polskilogopeda.pl"
markdown: kramdown

exclude: [
    LICENSE,
    README.md,
    SEO.md,
    package*.json,
    node_modules,
    dev-deploy.sh,
    .gitignore,
    .idea,
    src,
    Gemfile*,
    webpack*,
    img/blog/conv.sh
]

keep_files: [
  assets
]
