encoding: utf-8
livereload: true

# Build settings
markdown: kramdown

exclude: [
    LICENSE,
    README.md,
    SEO.md,
    package*.json,
    node_modules,
    dev-deploy.sh,
    .gitignore,
    .idea,
    src,
    Gemfile*,
    webpack*
]

keep_files: [
  assets
]

plugins:
  - jekyll-sitemap